"""enums change

Revision ID: 482954b55b70
Revises: 975e495fd402
Create Date: 2026-08-31 12:33:56.242208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '482954b55b70'
down_revision: Union[str, Sequence[str], None] = '975e495fd402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###