"""time for annotations

Revision ID: 5322c282407f
Revises: ai_suggestions
Create Date: 2026-08-30 16:22:15.556902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5322c282407f'
down_revision: Union[str, Sequence[str], None] = 'ai_suggestions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_ai_suggestions_status'), 'ai_suggestions', type_='check')
    op.add_column('annotations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('annotations_entity'), table_name='annotations')
    op.drop_index(op.f('annotations_scene'), table_name='annotations')
    op.drop_constraint(op.f('ck_annotations_source'), 'annotations', type_='check')
    op.drop_index(op.f('scenes_screenplay_order'), table_name='scenes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('scenes_screenplay_order'), 'scenes', ['screenplay_id', 'order_key'], unique=False)
    op.create_check_constraint(op.f('ck_annotations_source'), 'annotations', "source = ANY (ARRAY['manual'::text, 'ai_accepted'::text])")
    op.create_index(op.f('annotations_scene'), 'annotations', ['scene_id'], unique=False)
    op.create_index(op.f('annotations_entity'), 'annotations', ['entity_id'], unique=False)
    op.drop_column('annotations', 'updated_at')
    op.create_check_constraint(op.f('ck_ai_suggestions_status'), 'ai_suggestions', "status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text])")
    # ### end Alembic commands ###