"""enums 

Revision ID: 975e495fd402
Revises: 5322c282407f
Create Date: 2026-08-30 20:03:08.318193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '975e495fd402'
down_revision: Union[str, Sequence[str], None] = '5322c282407f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###