"""enums changes

Revision ID: d4cdb1784a81
Revises: 482954b55b70
Create Date: 2026-08-31 13:27:35.371775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4cdb1784a81'
down_revision: Union[str, Sequence[str], None] = '482954b55b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###